version: "3"

services:
  web:
    build: ./client
    container_name: client
    stdin_open: true
    tty: true
    environment:
      - TARGET_DOMAIN=<some_domain>
      - TARGET_PORT=<some_port>
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      - PORT=<some_port>
      - REDIS_HOST=<some_host>
      - REDIS_PORT=6379
      - DB_STRING=<some_string>

  redis:
    image: "redis:6.2.6-alpine3.14"
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
