import { redisFunctions } from ".";
import { Player } from "../models";
import { helpers } from ".";
import faker from "faker";
import { redisConstants } from "../constants";

// Method to create a sample 5000 player database with user names varying from Mock User {number}
// Foreach player a player profile hash within redis is also created, the object id generated by the mongoose driver as the key of the hash
// A 0 amount prize pool is also set.

export default async () => {
  for (let i = 0; i < 5000; i++) {
    const { _id, name, country, money, userName } = await new Player({
      userName: `Mock User ${i}`,
      name: faker.name.findName(),
      country: helpers.getRandomCountry(),
    }).save();

    await redisFunctions.setPlayerProfile(
      _id,
      redisConstants.playerHashFields.name,
      name,
      redisConstants.playerHashFields.userName,
      userName,
      redisConstants.playerHashFields.country,
      country,
      redisConstants.playerHashFields.money,
      money,
      redisConstants.playerHashFields.eRank,
      -1
    );
  }

  await redisFunctions.createPrizePool();
};
